use reqwest::blocking::Client;
use serde::{Deserialize, Serialize};
use serde_json::json;
use serde_json::Value;

const RISM_SEARCH_URL: &str = "https://rism.online/search?rows=100";

fn main() {}

fn download_rism_institutions() {
    let http_client = Client::new();

    let response_language = "en";
    let mode = "institutions";
    let page_number = "1";
    let url = format!("{}&mode={}&page={}", RISM_SEARCH_URL, mode, page_number);

    let result_as_text = http_client
        .get(url)
        .header("Accept", "application/ld+json")
        .header("X-API-Accept-Language", response_language)
        .send()
        .expect("cannot execute the request")
        .text()
        .expect("cannot get contents");
    let result_as_json: Value =
        serde_json::from_str(result_as_text.as_str()).expect("cannot parse json");

    println!("{:?}", result_as_json);
}

// curl -H "Accept: application/ld+json" -H "X-API-Accept-Language: en" https://rism.online/search?mode=institutions&page=1&rows=100
#[test]
fn download_rism_institutions_test() {
    download_rism_institutions();
}

struct InstitutionsData {
    total_items: usize,
    next_url: String,
    items: Vec<InstitutionData>,
}

struct InstitutionData {
    url: String,
}

#[derive(Serialize, Deserialize, Debug)]
struct NextUrl {
    next: String,
}

/*
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rism: <https://rism.online/api/v1#> .

<https://rism.online/institutions/30000655> a rism:Institution ;
    rdfs:label "Staatsbibliothek zu Berlin - Preußischer Kulturbesitz, Musikabteilung, Berlin (D-B)"@none ;
    rism:hasCountryCodes "D" ;
    rism:hasSiglum "D-B" .

*/

/*
<http://data.rism.info/id/rismauthorities/ks30000655>
        cc:License            <http://creativecommons.org/licenses/by/3.0/de> ;
        owl:sameAs            <https://d-nb.info/gnd/2116114-8> ;
        foaf:homepage         <https://staatsbibliothek-berlin.de/> ;
        geonames:countryCode  "XA-DE" ;
        rdau:P61018           "Berlin" ;
        vcard:hasAddress      "Unter den Linden 8, 10117 Berlin, Germany, https://staatsbibliothek-berlin.de/, https://staatsbibliothek-berlin.de/die-staatsbibliothek/abteilungen/musik, tel: +49 / (0)30 / 266-435321, " ;
        gnd:variantNameForTheCorporateBody  _:b0 ;
        marcRole:oth          <http://data.rism.info/id/rismauthorities/ks30000931> ;
        gnd:CorporateBody     "Library" ;
        rdau:P60898           "13.391360682215971" ;
        marcRole:oth          <http://data.rism.info/id/rismauthorities/ks30060871> ;
        dct:identifier        "30000655" ;
        dc:creator            "Staatsbibliothek zu Berlin - Preußischer Kulturbesitz, Musikabteilung" ;
        rdau:P60897           "52.51838657131361" ;
        dc:identifier         "D-B" ;
        gnd:CorporateBody     "Institution" ;
        gnd:placeOfActivity   "Berlin" .
*/

#[test]
fn serde_json_test() {
    let data = json!(
        r#"
            {
            "id":"https://rism.online/search?mode=institutions",
            "type":"Collection",
            "totalItems":26650,
            "view":{
                "type":"PartialCollectionView",
                "first":"https://rism.online/search?mode=institutions",
                "next":"https://rism.online/search?mode=institutions&page=2",
                "last":"https://rism.online/search?mode=institutions&page=1333",
                "totalPages":1333,
                "thisPage":1
            },
            "items":[
                {
                    "id":"https://rism.online/institutions/30000882",
                    "label":{
                        "none":[
                        "Bayerische Staatsbibliothek, München (D-Mbs)"
                        ]
                    },
                    "type":"rism:Institution",
                    "typeLabel":{
                        "en":[
                        "Institution"
                        ]
                    },
                    "summary":{
                        "countryName":{
                        "label":{
                            "en":[
                                "Country"
                            ]
                        },
                        "value":{
                            "en":[
                                "Germany"
                            ]
                        }
                        },
                        "otherNames":{
                        "label":{
                            "en":[
                                "Other form of name"
                            ]
                        },
                        "value":{
                            "none":[
                                "Abteilung Handschriften und alte Drucke",
                                "Musikabteilung"
                            ]
                        }
                        },
                        "totalSources":{
                        "label":{
                            "en":[
                                "Sources"
                            ]
                        },
                        "value":{
                            "none":[
                                "133741"
                            ]
                        }
                        }
                    },
                    "flags":{
                        "numberOfSources":133741,
                        "linkedWithExternalRecord":true
                    }
                }
            ]
            }
        "#
    );

    // let institutions_data =

    // Parse the string of data into a Person object. This is exactly the
    // same function as the one that produced serde_json::Value above, but
    // now we are asking it for a Person as output.
    // let institutions_response: InstitutionsResponse = serde_json::from_str(data).expect("cannot parse json");

    // Do things just like with any other Rust data structure.
    // println!("{:?}", institutions_response);
}

#[test]
fn test_1() {
    let data = json!({
        "x": {
            "y": ["z", "zz"]
        }
    });

    println!("{:?}", data.pointer("/x/y").unwrap());
}

/*
{
   "id":"https://rism.online/search?mode=institutions",
   "type":"Collection",
   "totalItems":26650,
   "view":{
      "type":"PartialCollectionView",
      "first":"https://rism.online/search?mode=institutions",
      "next":"https://rism.online/search?mode=institutions&page=2",
      "last":"https://rism.online/search?mode=institutions&page=1333",
      "totalPages":1333,
      "thisPage":1
   },
   "items":[
      {
         "id":"https://rism.online/institutions/30000882",
         "label":{
            "none":[
               "Bayerische Staatsbibliothek, München (D-Mbs)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Germany"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Abteilung Handschriften und alte Drucke",
                     "Musikabteilung"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "133741"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":133741,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30000655",
         "label":{
            "none":[
               "Staatsbibliothek zu Berlin - Preußischer Kulturbesitz, Musikabteilung, Berlin (D-B)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Germany"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Stiftung Preußischer Kulturbesitz"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "99393"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":99393,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30001581",
         "label":{
            "none":[
               "The British Library, London (GB-Lbl)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "United Kingdom"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "88525"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":88525,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30000398",
         "label":{
            "none":[
               "Österreichische Nationalbibliothek, Musiksammlung, Wien (A-Wn)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Austria"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Albertina Museum",
                     "K. K. Hofbibliothek"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "70200"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":70200,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30000042",
         "label":{
            "none":[
               "Sächsische Landesbibliothek - Staats- und Universitätsbibliothek (SLUB), Dresden (D-Dl)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Germany"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "66310"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":66310,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30001488",
         "label":{
            "none":[
               "Bibliothèque nationale de France, Département de la Musique, Paris (F-Pn)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "France"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "38110"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":38110,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30000438",
         "label":{
            "none":[
               "Conservatoire royal de Bruxelles, Bibliothèque - Koninklijk Conservatorium Brussel, Bibliotheek, Bruxelles; Brussel (B-Bc)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Belgium"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Conservatoire royal de Musique, Bibliothèque"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "26360"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":26360,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30000006",
         "label":{
            "none":[
               "Kloster Einsiedeln, Musikbibliothek, Einsiedeln (CH-E)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Switzerland"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "26024"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":26024
         }
      },
      {
         "id":"https://rism.online/institutions/30000053",
         "label":{
            "none":[
               "Leipziger Stadtbibliothek - Musikbibliothek, Leipzig (D-LEm)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Germany"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Städtische Bibliotheken, Musikbibliothek"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "24837"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":24837
         }
      },
      {
         "id":"https://rism.online/institutions/30002492",
         "label":{
            "none":[
               "The Library of Congress, Music Division, Washington, D.C. (US-Wc)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "United States of America"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "24811"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":24811,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30002153",
         "label":{
            "none":[
               "Musik- och teaterbiblioteket, Stockholm (S-Skma)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Sweden"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Kungliga Musikaliska Akademiens Biblioteket",
                     "Statens Musiksamlingar"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "21956"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":21956,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30000440",
         "label":{
            "none":[
               "Bibliothèque royale de Belgique (KBR) - Koninklijke Bibliotheek van België (KBR), Bruxelles; Brussel (B-Br)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Belgium"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Bibliothèque royale Albert 1.er",
                     "Koninklijke Bibliotheek Albert I"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "20852"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":20852,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30000239",
         "label":{
            "none":[
               "Santini-Bibliothek, Münster (D-MÜs)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Germany"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Santini-Bibliothek im Bischöflichen Priesterseminar"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "20356"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":20356
         }
      },
      {
         "id":"https://rism.online/institutions/30006485",
         "label":{
            "none":[
               "Hochschule für Musik Franz Liszt, Hochschularchiv - Thüringisches Landesmusikarchiv (HSA - ThLMA), Weimar (D-WRha)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Germany"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "20275"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":20275
         }
      },
      {
         "id":"https://rism.online/institutions/30001740",
         "label":{
            "none":[
               "Museo internazionale e biblioteca della musica di Bologna, Bologna (I-Bc)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Italy"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Civico Museo Bibliografico Musicale G. B. Martini, Biblioteca"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "19786"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":19786,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30000225",
         "label":{
            "none":[
               "Staats- und Universitätsbibliothek Carl von Ossietzky, Musiksammlung, Hamburg (D-Hs)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Germany"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Bibliotheca Hamburgensis Publica [bis 1919]",
                     "Historische Bestände, Sondersammlungen, Musiksammlung, Theatersammlung",
                     "Stadtbibliothek Hamburg [bis 1919]"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "19350"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":19350,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30000083",
         "label":{
            "none":[
               "Národní knihovna České republiky, Praha (CZ-Pu)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Czech Republic"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Hudební oddělení",
                     "Universitní knihovna"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "18756"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":18756,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30002111",
         "label":{
            "none":[
               "Biblioteka Uniwersytecka, Wrocław (PL-WRu)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Poland"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Oddział Starych Druków",
                     "Oddział Zbiorów Muzycznych"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "17369"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":17369,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30001032",
         "label":{
            "none":[
               "Herzog August Bibliothek, Wolfenbüttel (D-W)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Germany"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "17078"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":17078,
            "linkedWithExternalRecord":true
         }
      },
      {
         "id":"https://rism.online/institutions/30000839",
         "label":{
            "none":[
               "Badische Landesbibliothek, Musiksammlung, Karlsruhe (D-KA)"
            ]
         },
         "type":"rism:Institution",
         "typeLabel":{
            "en":[
               "Institution"
            ]
         },
         "summary":{
            "countryName":{
               "label":{
                  "en":[
                     "Country"
                  ]
               },
               "value":{
                  "en":[
                     "Germany"
                  ]
               }
            },
            "otherNames":{
               "label":{
                  "en":[
                     "Other form of name"
                  ]
               },
               "value":{
                  "none":[
                     "Badische Landesbibliothek, Musikabteilung",
                     "Großherzoglich Badische Hof- und Landesbibliothek"
                  ]
               }
            },
            "totalSources":{
               "label":{
                  "en":[
                     "Sources"
                  ]
               },
               "value":{
                  "none":[
                     "16872"
                  ]
               }
            }
         },
         "flags":{
            "numberOfSources":16872,
            "linkedWithExternalRecord":true
         }
      }
   ],
   "facets":{
      "sigla":{
         "label":{
            "en":[
               "Sigla"
            ]
         },
         "alias":"sigla",
         "type":"rism:QueryFacet",
         "suggestions":"https://rism.online/suggest?alias=sigla&q=",
         "behaviours":{
            "label":{
               "none":[
                  "Behaviour"
               ]
            },
            "items":[
               {
                  "label":{
                     "none":[
                        "And"
                     ]
                  },
                  "value":"intersection"
               },
               {
                  "label":{
                     "none":[
                        "Or"
                     ]
                  },
                  "value":"union"
               }
            ],
            "default":"intersection",
            "current":"intersection"
         }
      },
      "hide-diamm-records":{
         "alias":"hide-diamm-records",
         "label":{
            "none":[
               "Hide DIAMM records"
            ]
         },
         "type":"rism:ToggleFacet",
         "value":"true"
      },
      "city":{
         "alias":"city",
         "label":{
            "en":[
               "City"
            ]
         },
         "type":"rism:SelectFacet",
         "items":[
            {
               "value":"Paris",
               "label":{
                  "none":[
                     "Paris"
                  ]
               },
               "count":795
            },
            {
               "value":"London",
               "label":{
                  "none":[
                     "London"
                  ]
               },
               "count":502
            },
            {
               "value":"Wien",
               "label":{
                  "none":[
                     "Wien"
                  ]
               },
               "count":435
            },
            {
               "value":"Berlin",
               "label":{
                  "none":[
                     "Berlin"
                  ]
               },
               "count":414
            },
            {
               "value":"Leipzig",
               "label":{
                  "none":[
                     "Leipzig"
                  ]
               },
               "count":387
            },
            {
               "value":"Warszawa",
               "label":{
                  "none":[
                     "Warszawa"
                  ]
               },
               "count":360
            },
            {
               "value":"Roma",
               "label":{
                  "none":[
                     "Roma"
                  ]
               },
               "count":292
            },
            {
               "value":"Praha",
               "label":{
                  "none":[
                     "Praha"
                  ]
               },
               "count":196
            },
            {
               "value":"M%C3%BCnchen",
               "label":{
                  "none":[
                     "München"
                  ]
               },
               "count":193
            },
            {
               "value":"New%20York%20City%2C%20NY",
               "label":{
                  "none":[
                     "New York City, NY"
                  ]
               },
               "count":159
            },
            {
               "value":"Milano",
               "label":{
                  "none":[
                     "Milano"
                  ]
               },
               "count":152
            },
            {
               "value":"Hamburg",
               "label":{
                  "none":[
                     "Hamburg"
                  ]
               },
               "count":142
            },
            {
               "value":"Dresden",
               "label":{
                  "none":[
                     "Dresden"
                  ]
               },
               "count":130
            },
            {
               "value":"Frankfurt%20am%20Main",
               "label":{
                  "none":[
                     "Frankfurt am Main"
                  ]
               },
               "count":125
            },
            {
               "value":"Augsburg",
               "label":{
                  "none":[
                     "Augsburg"
                  ]
               },
               "count":121
            },
            {
               "value":"Krak%C3%B3w",
               "label":{
                  "none":[
                     "Kraków"
                  ]
               },
               "count":121
            },
            {
               "value":"Bruxelles",
               "label":{
                  "none":[
                     "Bruxelles"
                  ]
               },
               "count":115
            },
            {
               "value":"N%C3%BCrnberg",
               "label":{
                  "none":[
                     "Nürnberg"
                  ]
               },
               "count":105
            },
            {
               "value":"Venezia",
               "label":{
                  "none":[
                     "Venezia"
                  ]
               },
               "count":104
            },
            {
               "value":"Z%C3%BCrich",
               "label":{
                  "none":[
                     "Zürich"
                  ]
               },
               "count":98
            },
            {
               "value":"Amsterdam",
               "label":{
                  "none":[
                     "Amsterdam"
                  ]
               },
               "count":97
            },
            {
               "value":"Napoli",
               "label":{
                  "none":[
                     "Napoli"
                  ]
               },
               "count":97
            },
            {
               "value":"Salzburg",
               "label":{
                  "none":[
                     "Salzburg"
                  ]
               },
               "count":92
            },
            {
               "value":"Firenze",
               "label":{
                  "none":[
                     "Firenze"
                  ]
               },
               "count":89
            },
            {
               "value":"Basel",
               "label":{
                  "none":[
                     "Basel"
                  ]
               },
               "count":87
            },
            {
               "value":"Bern",
               "label":{
                  "none":[
                     "Bern"
                  ]
               },
               "count":83
            },
            {
               "value":"Madrid",
               "label":{
                  "none":[
                     "Madrid"
                  ]
               },
               "count":82
            },
            {
               "value":"Bologna",
               "label":{
                  "none":[
                     "Bologna"
                  ]
               },
               "count":80
            },
            {
               "value":"Stuttgart",
               "label":{
                  "none":[
                     "Stuttgart"
                  ]
               },
               "count":78
            },
            {
               "value":"Innsbruck",
               "label":{
                  "none":[
                     "Innsbruck"
                  ]
               },
               "count":72
            },
            {
               "value":"Linz",
               "label":{
                  "none":[
                     "Linz"
                  ]
               },
               "count":71
            },
            {
               "value":"Pozna%C5%84",
               "label":{
                  "none":[
                     "Poznań"
                  ]
               },
               "count":71
            },
            {
               "value":"K%C3%B6ln",
               "label":{
                  "none":[
                     "Köln"
                  ]
               },
               "count":66
            },
            {
               "value":"Regensburg",
               "label":{
                  "none":[
                     "Regensburg"
                  ]
               },
               "count":64
            },
            {
               "value":"Sankt-Peterburg",
               "label":{
                  "none":[
                     "Sankt-Peterburg"
                  ]
               },
               "count":63
            },
            {
               "value":"Philadelphia%2C%20PA",
               "label":{
                  "none":[
                     "Philadelphia, PA"
                  ]
               },
               "count":61
            },
            {
               "value":"Breslau",
               "label":{
                  "none":[
                     "Breslau"
                  ]
               },
               "count":60
            },
            {
               "value":"Mainz",
               "label":{
                  "none":[
                     "Mainz"
                  ]
               },
               "count":60
            },
            {
               "value":"Luzern",
               "label":{
                  "none":[
                     "Luzern"
                  ]
               },
               "count":56
            },
            {
               "value":"Moskva",
               "label":{
                  "none":[
                     "Moskva"
                  ]
               },
               "count":56
            },
            {
               "value":"Torino",
               "label":{
                  "none":[
                     "Torino"
                  ]
               },
               "count":56
            },
            {
               "value":"Oxford",
               "label":{
                  "none":[
                     "Oxford"
                  ]
               },
               "count":52
            },
            {
               "value":"Erfurt",
               "label":{
                  "none":[
                     "Erfurt"
                  ]
               },
               "count":50
            },
            {
               "value":"Antwerpen",
               "label":{
                  "none":[
                     "Antwerpen"
                  ]
               },
               "count":49
            },
            {
               "value":"Dublin",
               "label":{
                  "none":[
                     "Dublin"
                  ]
               },
               "count":46
            },
            {
               "value":"Graz",
               "label":{
                  "none":[
                     "Graz"
                  ]
               },
               "count":46
            },
            {
               "value":"L%27viv",
               "label":{
                  "none":[
                     "L'viv"
                  ]
               },
               "count":46
            },
            {
               "value":"Barcelona",
               "label":{
                  "none":[
                     "Barcelona"
                  ]
               },
               "count":45
            },
            {
               "value":"Budapest",
               "label":{
                  "none":[
                     "Budapest"
                  ]
               },
               "count":44
            },
            {
               "value":"Gen%C3%A8ve",
               "label":{
                  "none":[
                     "Genève"
                  ]
               },
               "count":44
            },
            {
               "value":"Genova",
               "label":{
                  "none":[
                     "Genova"
                  ]
               },
               "count":43
            },
            {
               "value":"Karlsruhe",
               "label":{
                  "none":[
                     "Karlsruhe"
                  ]
               },
               "count":43
            },
            {
               "value":"Seoul",
               "label":{
                  "none":[
                     "Seoul"
                  ]
               },
               "count":43
            },
            {
               "value":"Tokyo",
               "label":{
                  "none":[
                     "Tokyo"
                  ]
               },
               "count":43
            },
            {
               "value":"W%C3%BCrzburg",
               "label":{
                  "none":[
                     "Würzburg"
                  ]
               },
               "count":42
            },
            {
               "value":"Braunschweig",
               "label":{
                  "none":[
                     "Braunschweig"
                  ]
               },
               "count":41
            },
            {
               "value":"Stockholm",
               "label":{
                  "none":[
                     "Stockholm"
                  ]
               },
               "count":41
            },
            {
               "value":"Weimar",
               "label":{
                  "none":[
                     "Weimar"
                  ]
               },
               "count":40
            },
            {
               "value":"K%C3%B8benhavn",
               "label":{
                  "none":[
                     "København"
                  ]
               },
               "count":39
            },
            {
               "value":"Lyon",
               "label":{
                  "none":[
                     "Lyon"
                  ]
               },
               "count":39
            },
            {
               "value":"Bratislava",
               "label":{
                  "none":[
                     "Bratislava"
                  ]
               },
               "count":37
            },
            {
               "value":"Jena",
               "label":{
                  "none":[
                     "Jena"
                  ]
               },
               "count":37
            },
            {
               "value":"Strasbourg",
               "label":{
                  "none":[
                     "Strasbourg"
                  ]
               },
               "count":36
            },
            {
               "value":"Boston%2C%20MA",
               "label":{
                  "none":[
                     "Boston, MA"
                  ]
               },
               "count":34
            },
            {
               "value":"Hannover",
               "label":{
                  "none":[
                     "Hannover"
                  ]
               },
               "count":34
            },
            {
               "value":"Magdeburg",
               "label":{
                  "none":[
                     "Magdeburg"
                  ]
               },
               "count":34
            },
            {
               "value":"Bonn",
               "label":{
                  "none":[
                     "Bonn"
                  ]
               },
               "count":32
            },
            {
               "value":"Li%C3%A8ge",
               "label":{
                  "none":[
                     "Liège"
                  ]
               },
               "count":32
            },
            {
               "value":"L%C3%BCbeck",
               "label":{
                  "none":[
                     "Lübeck"
                  ]
               },
               "count":32
            },
            {
               "value":"Ferrara",
               "label":{
                  "none":[
                     "Ferrara"
                  ]
               },
               "count":30
            },
            {
               "value":"Lisboa",
               "label":{
                  "none":[
                     "Lisboa"
                  ]
               },
               "count":30
            },
            {
               "value":"Cambridge",
               "label":{
                  "none":[
                     "Cambridge"
                  ]
               },
               "count":29
            },
            {
               "value":"Chicago%2C%20IL",
               "label":{
                  "none":[
                     "Chicago, IL"
                  ]
               },
               "count":29
            },
            {
               "value":"Danzig%3B%20Gda%C5%84sk",
               "label":{
                  "none":[
                     "Danzig; Gdańsk"
                  ]
               },
               "count":29
            },
            {
               "value":"Halle%20%28Saale%29",
               "label":{
                  "none":[
                     "Halle (Saale)"
                  ]
               },
               "count":29
            },
            {
               "value":"Kassel",
               "label":{
                  "none":[
                     "Kassel"
                  ]
               },
               "count":29
            },
            {
               "value":"Parma",
               "label":{
                  "none":[
                     "Parma"
                  ]
               },
               "count":29
            },
            {
               "value":"Washington%2C%20D.C.",
               "label":{
                  "none":[
                     "Washington, D.C."
                  ]
               },
               "count":29
            },
            {
               "value":"Zagreb",
               "label":{
                  "none":[
                     "Zagreb"
                  ]
               },
               "count":29
            },
            {
               "value":"Brno",
               "label":{
                  "none":[
                     "Brno"
                  ]
               },
               "count":28
            },
            {
               "value":"Den%20Haag",
               "label":{
                  "none":[
                     "Den Haag"
                  ]
               },
               "count":28
            },
            {
               "value":"D%C3%BCsseldorf",
               "label":{
                  "none":[
                     "Düsseldorf"
                  ]
               },
               "count":28
            },
            {
               "value":"Gotha",
               "label":{
                  "none":[
                     "Gotha"
                  ]
               },
               "count":28
            },
            {
               "value":"Fribourg",
               "label":{
                  "none":[
                     "Fribourg"
                  ]
               },
               "count":27
            },
            {
               "value":"G%C3%B6ttingen",
               "label":{
                  "none":[
                     "Göttingen"
                  ]
               },
               "count":27
            },
            {
               "value":"%C5%81%C3%B3d%C5%BA",
               "label":{
                  "none":[
                     "Łódź"
                  ]
               },
               "count":27
            },
            {
               "value":"Perugia",
               "label":{
                  "none":[
                     "Perugia"
                  ]
               },
               "count":26
            },
            {
               "value":"Freiburg%20im%20Breisgau",
               "label":{
                  "none":[
                     "Freiburg im Breisgau"
                  ]
               },
               "count":25
            },
            {
               "value":"Gent",
               "label":{
                  "none":[
                     "Gent"
                  ]
               },
               "count":25
            },
            {
               "value":"Palermo",
               "label":{
                  "none":[
                     "Palermo"
                  ]
               },
               "count":25
            },
            {
               "value":"T%C3%BCbingen",
               "label":{
                  "none":[
                     "Tübingen"
                  ]
               },
               "count":25
            },
            {
               "value":"Darmstadt",
               "label":{
                  "none":[
                     "Darmstadt"
                  ]
               },
               "count":24
            },
            {
               "value":"Hall%20in%20Tirol",
               "label":{
                  "none":[
                     "Hall in Tirol"
                  ]
               },
               "count":24
            },
            {
               "value":"Speyer",
               "label":{
                  "none":[
                     "Speyer"
                  ]
               },
               "count":24
            },
            {
               "value":"Brescia",
               "label":{
                  "none":[
                     "Brescia"
                  ]
               },
               "count":23
            },
            {
               "value":"Coburg",
               "label":{
                  "none":[
                     "Coburg"
                  ]
               },
               "count":23
            },
            {
               "value":"Edinburgh",
               "label":{
                  "none":[
                     "Edinburgh"
                  ]
               },
               "count":23
            },
            {
               "value":"Kyung-sung%20%28%E4%BA%AC%E5%9F%8E%29",
               "label":{
                  "none":[
                     "Kyung-sung (京城)"
                  ]
               },
               "count":23
            },
            {
               "value":"Mannheim",
               "label":{
                  "none":[
                     "Mannheim"
                  ]
               },
               "count":23
            },
            {
               "value":"Modena",
               "label":{
                  "none":[
                     "Modena"
                  ]
               },
               "count":23
            },
            {
               "value":"M%C3%BCnster",
               "label":{
                  "none":[
                     "Münster"
                  ]
               },
               "count":23
            },
            {
               "value":"Passau",
               "label":{
                  "none":[
                     "Passau"
                  ]
               },
               "count":23
            },
            {
               "value":"%C4%B0stanbul",
               "label":{
                  "none":[
                     "İstanbul"
                  ]
               },
               "count":23
            },
            {
               "value":"Dessau",
               "label":{
                  "none":[
                     "Dessau"
                  ]
               },
               "count":22
            },
            {
               "value":"Pisa",
               "label":{
                  "none":[
                     "Pisa"
                  ]
               },
               "count":22
            },
            {
               "value":"Rostock",
               "label":{
                  "none":[
                     "Rostock"
                  ]
               },
               "count":22
            },
            {
               "value":"Solothurn",
               "label":{
                  "none":[
                     "Solothurn"
                  ]
               },
               "count":22
            },
            {
               "value":"Trento",
               "label":{
                  "none":[
                     "Trento"
                  ]
               },
               "count":22
            },
            {
               "value":"Zug",
               "label":{
                  "none":[
                     "Zug"
                  ]
               },
               "count":22
            },
            {
               "value":"Bamberg",
               "label":{
                  "none":[
                     "Bamberg"
                  ]
               },
               "count":21
            },
            {
               "value":"Bergamo",
               "label":{
                  "none":[
                     "Bergamo"
                  ]
               },
               "count":21
            },
            {
               "value":"Leuven",
               "label":{
                  "none":[
                     "Leuven"
                  ]
               },
               "count":21
            },
            {
               "value":"Lucca",
               "label":{
                  "none":[
                     "Lucca"
                  ]
               },
               "count":21
            },
            {
               "value":"Padova",
               "label":{
                  "none":[
                     "Padova"
                  ]
               },
               "count":21
            },
            {
               "value":"Ulm",
               "label":{
                  "none":[
                     "Ulm"
                  ]
               },
               "count":21
            },
            {
               "value":"Bari",
               "label":{
                  "none":[
                     "Bari"
                  ]
               },
               "count":20
            },
            {
               "value":"Bremen",
               "label":{
                  "none":[
                     "Bremen"
                  ]
               },
               "count":20
            },
            {
               "value":"Heidelberg",
               "label":{
                  "none":[
                     "Heidelberg"
                  ]
               },
               "count":20
            },
            {
               "value":"St.%20Gallen",
               "label":{
                  "none":[
                     "St. Gallen"
                  ]
               },
               "count":20
            },
            {
               "value":"Wroc%C5%82aw",
               "label":{
                  "none":[
                     "Wrocław"
                  ]
               },
               "count":20
            },
            {
               "value":"Zittau",
               "label":{
                  "none":[
                     "Zittau"
                  ]
               },
               "count":20
            },
            {
               "value":"Jerusalem",
               "label":{
                  "none":[
                     "Jerusalem"
                  ]
               },
               "count":19
            },
            {
               "value":"Rudolstadt",
               "label":{
                  "none":[
                     "Rudolstadt"
                  ]
               },
               "count":19
            },
            {
               "value":"Vicenza",
               "label":{
                  "none":[
                     "Vicenza"
                  ]
               },
               "count":19
            },
            {
               "value":"Bautzen",
               "label":{
                  "none":[
                     "Bautzen"
                  ]
               },
               "count":18
            },
            {
               "value":"Breslau%3B%20Wroc%C5%82aw",
               "label":{
                  "none":[
                     "Breslau; Wrocław"
                  ]
               },
               "count":18
            },
            {
               "value":"Ciudad%20de%20M%C3%A9xico",
               "label":{
                  "none":[
                     "Ciudad de México"
                  ]
               },
               "count":18
            },
            {
               "value":"Frankfurt%20%28Oder%29",
               "label":{
                  "none":[
                     "Frankfurt (Oder)"
                  ]
               },
               "count":18
            },
            {
               "value":"Kyjiv",
               "label":{
                  "none":[
                     "Kyjiv"
                  ]
               },
               "count":18
            },
            {
               "value":"K%C3%B6nigsberg%20%28Preu%C3%9Fen%29",
               "label":{
                  "none":[
                     "Königsberg (Preußen)"
                  ]
               },
               "count":18
            },
            {
               "value":"Lille",
               "label":{
                  "none":[
                     "Lille"
                  ]
               },
               "count":18
            },
            {
               "value":"Montr%C3%A9al",
               "label":{
                  "none":[
                     "Montréal"
                  ]
               },
               "count":18
            },
            {
               "value":"Trier",
               "label":{
                  "none":[
                     "Trier"
                  ]
               },
               "count":18
            },
            {
               "value":"Vilnius",
               "label":{
                  "none":[
                     "Vilnius"
                  ]
               },
               "count":18
            },
            {
               "value":"Wittenberg",
               "label":{
                  "none":[
                     "Wittenberg"
                  ]
               },
               "count":18
            },
            {
               "value":"Ath%C4%93nai",
               "label":{
                  "none":[
                     "Athēnai"
                  ]
               },
               "count":17
            },
            {
               "value":"Lublin",
               "label":{
                  "none":[
                     "Lublin"
                  ]
               },
               "count":17
            },
            {
               "value":"Prague",
               "label":{
                  "none":[
                     "Prague"
                  ]
               },
               "count":17
            },
            {
               "value":"Wolfenb%C3%BCttel",
               "label":{
                  "none":[
                     "Wolfenbüttel"
                  ]
               },
               "count":17
            },
            {
               "value":"Aachen",
               "label":{
                  "none":[
                     "Aachen"
                  ]
               },
               "count":16
            },
            {
               "value":"Buenos%20Aires",
               "label":{
                  "none":[
                     "Buenos Aires"
                  ]
               },
               "count":16
            },
            {
               "value":"Fulda",
               "label":{
                  "none":[
                     "Fulda"
                  ]
               },
               "count":16
            },
            {
               "value":"Kiel",
               "label":{
                  "none":[
                     "Kiel"
                  ]
               },
               "count":16
            },
            {
               "value":"Lw%C3%B3w%3B%20L%27viv",
               "label":{
                  "none":[
                     "Lwów; L'viv"
                  ]
               },
               "count":16
            },
            {
               "value":"L%C3%BCneburg",
               "label":{
                  "none":[
                     "Lüneburg"
                  ]
               },
               "count":16
            },
            {
               "value":"Meiningen",
               "label":{
                  "none":[
                     "Meiningen"
                  ]
               },
               "count":16
            },
            {
               "value":"Sankt%20Gallen",
               "label":{
                  "none":[
                     "Sankt Gallen"
                  ]
               },
               "count":16
            },
            {
               "value":"Siena",
               "label":{
                  "none":[
                     "Siena"
                  ]
               },
               "count":16
            },
            {
               "value":"Stettin%3B%20Szczecin",
               "label":{
                  "none":[
                     "Stettin; Szczecin"
                  ]
               },
               "count":16
            },
            {
               "value":"Sydney",
               "label":{
                  "none":[
                     "Sydney"
                  ]
               },
               "count":16
            },
            {
               "value":"Trieste",
               "label":{
                  "none":[
                     "Trieste"
                  ]
               },
               "count":16
            },
            {
               "value":"Utrecht",
               "label":{
                  "none":[
                     "Utrecht"
                  ]
               },
               "count":16
            },
            {
               "value":"Verona",
               "label":{
                  "none":[
                     "Verona"
                  ]
               },
               "count":16
            },
            {
               "value":"Granada",
               "label":{
                  "none":[
                     "Granada"
                  ]
               },
               "count":15
            },
            {
               "value":"Katowice",
               "label":{
                  "none":[
                     "Katowice"
                  ]
               },
               "count":15
            },
            {
               "value":"Kyoto",
               "label":{
                  "none":[
                     "Kyoto"
                  ]
               },
               "count":15
            },
            {
               "value":"Los%20Angeles%2C%20CA",
               "label":{
                  "none":[
                     "Los Angeles, CA"
                  ]
               },
               "count":15
            },
            {
               "value":"Mantova",
               "label":{
                  "none":[
                     "Mantova"
                  ]
               },
               "count":15
            },
            {
               "value":"Toronto",
               "label":{
                  "none":[
                     "Toronto"
                  ]
               },
               "count":15
            },
            {
               "value":"Val%C3%A8ncia",
               "label":{
                  "none":[
                     "València"
                  ]
               },
               "count":15
            },
            {
               "value":"Wien%20%28Vienna%29",
               "label":{
                  "none":[
                     "Wien (Vienna)"
                  ]
               },
               "count":15
            },
            {
               "value":"Bolzano",
               "label":{
                  "none":[
                     "Bolzano"
                  ]
               },
               "count":14
            },
            {
               "value":"Brixen",
               "label":{
                  "none":[
                     "Brixen"
                  ]
               },
               "count":14
            },
            {
               "value":"Brixen%3B%20Bressanone",
               "label":{
                  "none":[
                     "Brixen; Bressanone"
                  ]
               },
               "count":14
            },
            {
               "value":"Chur",
               "label":{
                  "none":[
                     "Chur"
                  ]
               },
               "count":14
            },
            {
               "value":"Eichst%C3%A4tt",
               "label":{
                  "none":[
                     "Eichstätt"
                  ]
               },
               "count":14
            },
            {
               "value":"Kempten",
               "label":{
                  "none":[
                     "Kempten"
                  ]
               },
               "count":14
            },
            {
               "value":"Konstanz",
               "label":{
                  "none":[
                     "Konstanz"
                  ]
               },
               "count":14
            },
            {
               "value":"Lausanne",
               "label":{
                  "none":[
                     "Lausanne"
                  ]
               },
               "count":14
            },
            {
               "value":"Marburg",
               "label":{
                  "none":[
                     "Marburg"
                  ]
               },
               "count":14
            },
            {
               "value":"Mechelen",
               "label":{
                  "none":[
                     "Mechelen"
                  ]
               },
               "count":14
            },
            {
               "value":"Piacenza",
               "label":{
                  "none":[
                     "Piacenza"
                  ]
               },
               "count":14
            },
            {
               "value":"Pistoia",
               "label":{
                  "none":[
                     "Pistoia"
                  ]
               },
               "count":14
            },
            {
               "value":"P%C5%82ock",
               "label":{
                  "none":[
                     "Płock"
                  ]
               },
               "count":14
            },
            {
               "value":"Rastatt",
               "label":{
                  "none":[
                     "Rastatt"
                  ]
               },
               "count":14
            },
            {
               "value":"Rotterdam",
               "label":{
                  "none":[
                     "Rotterdam"
                  ]
               },
               "count":14
            },
            {
               "value":"Sulmona",
               "label":{
                  "none":[
                     "Sulmona"
                  ]
               },
               "count":14
            },
            {
               "value":"Wiesbaden",
               "label":{
                  "none":[
                     "Wiesbaden"
                  ]
               },
               "count":14
            },
            {
               "value":"Winterthur",
               "label":{
                  "none":[
                     "Winterthur"
                  ]
               },
               "count":14
            },
            {
               "value":"Aghion%20Oros",
               "label":{
                  "none":[
                     "Aghion Oros"
                  ]
               },
               "count":13
            },
            {
               "value":"Alt%C3%B6tting",
               "label":{
                  "none":[
                     "Altötting"
                  ]
               },
               "count":13
            },
            {
               "value":"Bayreuth",
               "label":{
                  "none":[
                     "Bayreuth"
                  ]
               },
               "count":13
            },
            {
               "value":"Burgos",
               "label":{
                  "none":[
                     "Burgos"
                  ]
               },
               "count":13
            },
            {
               "value":"Cagliari",
               "label":{
                  "none":[
                     "Cagliari"
                  ]
               },
               "count":13
            },
            {
               "value":"Eisenach",
               "label":{
                  "none":[
                     "Eisenach"
                  ]
               },
               "count":13
            },
            {
               "value":"Firenze%20%28Florence%29",
               "label":{
                  "none":[
                     "Firenze (Florence)"
                  ]
               },
               "count":13
            },
            {
               "value":"Hildesheim",
               "label":{
                  "none":[
                     "Hildesheim"
                  ]
               },
               "count":13
            },
            {
               "value":"Kalisz",
               "label":{
                  "none":[
                     "Kalisz"
                  ]
               },
               "count":13
            },
            {
               "value":"Leiden",
               "label":{
                  "none":[
                     "Leiden"
                  ]
               },
               "count":13
            },
            {
               "value":"Ljubljana",
               "label":{
                  "none":[
                     "Ljubljana"
                  ]
               },
               "count":13
            },
            {
               "value":"Messina",
               "label":{
                  "none":[
                     "Messina"
                  ]
               },
               "count":13
            },
            {
               "value":"Pavia",
               "label":{
                  "none":[
                     "Pavia"
                  ]
               },
               "count":13
            },
            {
               "value":"Rome",
               "label":{
                  "none":[
                     "Rome"
                  ]
               },
               "count":13
            },
            {
               "value":"Rouen",
               "label":{
                  "none":[
                     "Rouen"
                  ]
               },
               "count":13
            },
            {
               "value":"Salamanca",
               "label":{
                  "none":[
                     "Salamanca"
                  ]
               },
               "count":13
            },
            {
               "value":"Zaragoza",
               "label":{
                  "none":[
                     "Zaragoza"
                  ]
               },
               "count":13
            },
            {
               "value":"Zwickau",
               "label":{
                  "none":[
                     "Zwickau"
                  ]
               },
               "count":13
            },
            {
               "value":"Aalst",
               "label":{
                  "none":[
                     "Aalst"
                  ]
               },
               "count":12
            },
            {
               "value":"Arezzo",
               "label":{
                  "none":[
                     "Arezzo"
                  ]
               },
               "count":12
            },
            {
               "value":"Cambridge%2C%20MA",
               "label":{
                  "none":[
                     "Cambridge, MA"
                  ]
               },
               "count":12
            }
         ],
         "defaultSort":"count",
         "behaviours":{
            "label":{
               "none":[
                  "Behaviour"
               ]
            },
            "items":[
               {
                  "label":{
                     "none":[
                        "And"
                     ]
                  },
                  "value":"intersection"
               },
               {
                  "label":{
                     "none":[
                        "Or"
                     ]
                  },
                  "value":"union"
               }
            ],
            "default":"intersection",
            "current":"intersection"
         }
      },
      "has-siglum":{
         "alias":"has-siglum",
         "label":{
            "none":[
               "Has siglum"
            ]
         },
         "type":"rism:ToggleFacet",
         "value":"true"
      },
      "roles":{
         "alias":"roles",
         "label":{
            "en":[
               "Role"
            ]
         },
         "type":"rism:SelectFacet",
         "items":[
            {
               "value":"pbl",
               "label":{
                  "en":[
                     "Publisher"
                  ]
               },
               "count":9529
            },
            {
               "value":"fmo",
               "label":{
                  "en":[
                     "Former owner"
                  ]
               },
               "count":2676
            },
            {
               "value":"prt",
               "label":{
                  "en":[
                     "Printer"
                  ]
               },
               "count":1567
            },
            {
               "value":"oth",
               "label":{
                  "en":[
                     "Other"
                  ]
               },
               "count":1437
            },
            {
               "value":"dte",
               "label":{
                  "en":[
                     "Dedicatee"
                  ]
               },
               "count":1235
            },
            {
               "value":"dst",
               "label":{
                  "en":[
                     "Distributor"
                  ]
               },
               "count":514
            },
            {
               "value":"prf",
               "label":{
                  "en":[
                     "Performer"
                  ]
               },
               "count":310
            },
            {
               "value":"bsl",
               "label":{
                  "en":[
                     "Bookseller"
                  ]
               },
               "count":309
            },
            {
               "value":"asn",
               "label":{
                  "en":[
                     "Associated name"
                  ]
               },
               "count":286
            },
            {
               "value":"evp",
               "label":{
                  "en":[
                     "Event place"
                  ]
               },
               "count":256
            },
            {
               "value":"edt",
               "label":{
                  "en":[
                     "Editor"
                  ]
               },
               "count":124
            },
            {
               "value":"dpt",
               "label":{
                  "en":[
                     "Depositor"
                  ]
               },
               "count":120
            },
            {
               "value":"cph",
               "label":{
                  "en":[
                     "Copyright holder"
                  ]
               },
               "count":84
            },
            {
               "value":"scr",
               "label":{
                  "en":[
                     "Copyist"
                  ]
               },
               "count":69
            },
            {
               "value":"ppm",
               "label":{
                  "en":[
                     "Papermaker"
                  ]
               },
               "count":65
            },
            {
               "value":"lse",
               "label":{
                  "en":[
                     "Licensee"
                  ]
               },
               "count":21
            },
            {
               "value":"pat",
               "label":{
                  "none":[
                     "pat"
                  ]
               },
               "count":21
            },
            {
               "value":"asg",
               "label":{
                  "en":[
                     "Assignee"
                  ]
               },
               "count":16
            },
            {
               "value":"tyd",
               "label":{
                  "en":[
                     "Type designer"
                  ]
               },
               "count":11
            },
            {
               "value":"cmp",
               "label":{
                  "en":[
                     "Composer"
                  ]
               },
               "count":1
            }
         ],
         "defaultSort":"count",
         "behaviours":{
            "label":{
               "none":[
                  "Behaviour"
               ]
            },
            "items":[
               {
                  "label":{
                     "none":[
                        "And"
                     ]
                  },
                  "value":"intersection"
               },
               {
                  "label":{
                     "none":[
                        "Or"
                     ]
                  },
                  "value":"union"
               }
            ],
            "default":"intersection",
            "current":"intersection"
         }
      },
      "number-sources":{
         "alias":"number-sources",
         "label":{
            "none":[
               "Number of sources"
            ]
         },
         "type":"rism:SelectFacet",
         "items":[
            {
               "value":"1",
               "label":{
                  "none":[
                     "1"
                  ]
               },
               "count":7872
            },
            {
               "value":"2%20to%2010",
               "label":{
                  "none":[
                     "2 to 10"
                  ]
               },
               "count":5923
            },
            {
               "value":"11%20to%20100",
               "label":{
                  "none":[
                     "11 to 100"
                  ]
               },
               "count":2632
            },
            {
               "value":"more%20than%20100",
               "label":{
                  "none":[
                     "more than 100"
                  ]
               },
               "count":1848
            }
         ],
         "defaultSort":"count",
         "behaviours":{
            "label":{
               "none":[
                  "Behaviour"
               ]
            },
            "items":[
               {
                  "label":{
                     "none":[
                        "And"
                     ]
                  },
                  "value":"intersection"
               },
               {
                  "label":{
                     "none":[
                        "Or"
                     ]
                  },
                  "value":"union"
               }
            ],
            "default":"intersection",
            "current":"intersection"
         }
      }
   },
   "modes":{
      "alias":"mode",
      "label":{
         "none":[
            "Result type"
         ]
      },
      "type":"rism:ModeFacet",
      "items":[
         {
            "value":"sources",
            "label":{
               "en":[
                  "Sources"
               ]
            },
            "count":1554114
         },
         {
            "value":"people",
            "label":{
               "en":[
                  "People"
               ]
            },
            "count":152547
         },
         {
            "value":"institutions",
            "label":{
               "en":[
                  "Institutions"
               ]
            },
            "count":26650
         },
         {
            "value":"incipits",
            "label":{
               "en":[
                  "Incipits"
               ]
            },
            "count":2436432
         }
      ]
   },
   "sorts":{
      "options":[
         {
            "label":{
               "none":[
                  "Most relevant"
               ]
            },
            "alias":"relevance"
         },
         {
            "label":{
               "none":[
                  "Alphabetical (Name, A-Z)"
               ]
            },
            "alias":"alphabetical-name"
         },
         {
            "label":{
               "none":[
                  "Date Added (Newest first)"
               ]
            },
            "alias":"date-added"
         },
         {
            "label":{
               "none":[
                  "Number of sources"
               ]
            },
            "alias":"num-sources"
         }
      ],
      "default":"relevance"
   },
   "pageSizes":[
      "20",
      "40",
      "100"
   ]
}
*/
